//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldProjectWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyMaster
    {
        public int PID { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public string ConactPerson { get; set; }
        public string PartyAdd1 { get; set; }
        public string PartyAdd2 { get; set; }
        public string PartyAdd3 { get; set; }
        public string PinCode { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
    }
}
