//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldProjectWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMan
    {
        public int SMID { get; set; }
        public string SMCode { get; set; }
        public string SMName { get; set; }
    }
}
