//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldProjectWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerMaster
    {
        public int WID { get; set; }
        public string WorkerCode { get; set; }
        public string WorkerName { get; set; }
        public string ConactPerson { get; set; }
        public string WorkerAdd1 { get; set; }
        public string WorkerAdd2 { get; set; }
        public string WorkerAdd3 { get; set; }
        public string PinCode { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Working { get; set; }
        public string SectionCode { get; set; }
    }
}
